# Generated by Django 6.0.6 on 2026-06-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='weather',
        ),
    ]
