# Generated by Django 6.0.6 on 2026-06-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_product_category_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('飲み物', '飲み物'), ('食べ物', '食べ物'), ('デザート', 'デザート')], default='飲み物', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
