# Generated by Django 6.0.6 on 2026-06-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_product_category_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt_no',
            field=models.CharField(default='000000', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='temperature',
            field=models.FloatField(default=15.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='weather',
            field=models.CharField(choices=[('晴れ', '晴れ'), ('曇り', '曇り'), ('雨', '雨'), ('雪', '雪')], default='晴れ', max_length=10),
            preserve_default=False,
        ),
    ]
